baseURL                = "https://irkode.github.io/zero2hugo/"
defaultContentLanguage = "en"
title                  = "Zero 2 Hugo - A Website Primer"

disableKinds = ['RSS', 'sitemap', 'taxonomy', 'term']

enableGitInfo = true

[permalinks]
   [permalinks.page]
      '/examples' = '/:sections/:slug'

[params]
   debugTemplate = true

[module]
   # workaround for -cleanDestinationDir without having need for a static folder: https://github.com/gohugoio/hugo/issues/8433
   [[module.mounts]]
      target       = 'static'
      source       = 'static'
      excludeFiles = [".keep"]

   [[module.mounts]]
      source = "content"
      target = "content"
   [[module.mounts]]
      source       = "examples"
      target       = "content/examples"
      includeFiles = ["**/*.md", "/layouts/*"]
      excludeFiles = ["resources/**", "public/**", ".hugo_build.lock"]
[build]
   [build.buildStats]
      enable = false
   [[build.cachebusters]]
      source = 'assets/.*\.(.*)$'
      target = '$1'
