baseURL = "https://irkode.github.io/zero2hugo/"
defaultContentLanguage = "en"
title = "Zero 2 Hugo - A Website Primer"

disableKinds = ['RSS', 'sitemap', 'taxonomy', 'term']

enableGitInfo = true

[permalinks]
   [permalinks.page]
      '/examples' = '/:section/:slug'
      '/primer' = '/:section/:slug'

[params]
   titleShort = "Zero 2 Hugo"
   sitePrefix = "Z2H"

[module]
   # default mounts (neccessary as we mount around with these. see [Module configuration: mounts](https://gohugo.io/hugo-modules/configuration/#module-configuration-mounts)
   # [[module.mounts]]
   #    source = "assets"
   #    target = "assets"
   # [[module.mounts]]
   #    source = "content"
   #    target = "content"

   # [[module.mounts]]
   #    source = "/examples"
   #    target = "assets/examples"
   #    excludeFiles = ["/**/public/", "/**/resources/", "/.hugo_build.lock"]