baseURL = "https://irkode.github.io/zero2hugo/"
defaultContentLanguage = "en"
title = "Zero 2 Hugo - A Website Primer"

disableKinds = ['RSS', 'sitemap', 'taxonomy', 'term']

enableGitInfo = true

[permalinks]
   [permalinks.page]
      '/examples' = '/:section/:slug'

[params]
   titleShort = "Zero 2 Hugo"
   sitePrefix = "Z2H"

[module]
   # workaround for -cleanDestinationDir without having need for a static folder: https://github.com/gohugoio/hugo/issues/8433
   [[module.mounts]]
      target = 'static'
      source = 'static'
      excludeFiles = [".keep"]

      # [[module.mounts]]
      #    source = "content"
      #    target = "content"
      # [[module.mounts]]
      #    source = "/examples"
      #    target = "content/examples"
      #    includeFiles = ["/**/*.md"]
      #      excludeFiles = ["/**/public/", "/**/resources/", "/.hugo_build.lock"]

# was unable to turn that completely off. disliked the debug messages for missing tailwind css
[build]
   [build.buildStats]
      enable = false
   [[build.cachebusters]]
      source = 'assets/.*\.(.*)$'
      target = '$1'
